# Generated by Django 2.0 on 2018-08-28 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_source', models.URLField(validators=[django.core.validators.URLValidator])),
                ('name', models.CharField(default='some deck', max_length=255, verbose_name='デッキ名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='url',
            new_name='card_source',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='url',
            new_name='card_source',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='owner',
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_manager.UserDecks'),
        ),
    ]
